version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - D:\DockerApps\mysql_data:/var/lib/mysql

volumes:
  mysql_data:
